theme: jekyll-theme-slate
google_analytics:
  tracking_id: G-07HMEZSNLP
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yoojeeho.github.io/" # the base hostname & protocol for your site
